info:
  name: listTasks
  type: http
  seq: 1
  tags:
    - Tasks

http:
  method: GET
  url: "{{baseUrl}}/tasks"
  params:
    - name: status
      value: inbox
      type: query
      disabled: true
    - name: status
      value: next
      type: query
      disabled: true
    - name: status
      value: waiting
      type: query
      disabled: true
    - name: status
      value: someday
      type: query
      disabled: true
    - name: status
      value: done
      type: query
      disabled: true
    - name: projectId
      value: ""
      type: query
      disabled: true
    - name: tagId
      value: ""
      type: query
      disabled: true
    - name: limit
      value: "50"
      type: query
    - name: offset
      value: "0"
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Task list
    request:
      url: "{{baseUrl}}/tasks"
      method: GET
      params:
        - name: status
          value: inbox
          type: query
          disabled: true
        - name: status
          value: next
          type: query
          disabled: true
        - name: status
          value: waiting
          type: query
          disabled: true
        - name: status
          value: someday
          type: query
          disabled: true
        - name: status
          value: done
          type: query
          disabled: true
        - name: projectId
          value: ""
          type: query
          disabled: true
        - name: tagId
          value: ""
          type: query
          disabled: true
        - name: limit
          value: "50"
          type: query
        - name: offset
          value: "0"
          type: query
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "items": [
              {
                "id": "",
                "title": "",
                "notes": "",
                "status": "inbox",
                "projectId": "",
                "tags": [
                  {
                    "id": "",
                    "name": "",
                    "createdAt": ""
                  }
                ],
                "dueAt": "",
                "completedAt": "",
                "createdAt": "",
                "updatedAt": ""
              }
            ]
          }
